### ISSUE TITLE
Play Store link not working..!

### ISSUE THREAD

**Issue by srikanth7785** [apgapg/flutter_profile#1]
The Play Store link that you have mentioned in the repository is not working..it shows.. item not found..

**Comment by srikanth7785** [comment]
> @apgapg

**Comment by apgapg** [comment]
Hi! Playstore recently removed my app may due to some personal violations. Hence the link is broken.

**Comment by srikanth7785** [comment]
Ohh..ok fine..!

So, you better update the link or remove it completely.

**Comment by apgapg** [comment]
Fixed. I have added website link for checking demo
