### ISSUE TITLE
Bug in Teaching Section

### ISSUE THREAD

**Issue by venkivijay** [apgapg/flutter_profile#5]
The testimonials in the teaching section are out of the view.
And the word "Teaching" itself is not so visible in the white background.

[Screenshot of the bug](https://imgur.com/CrrhsZi)

**Comment by apgapg** [comment]
Hi @venkivijay the project was originally made for  mobile only. Flutter web came later and hence i never nade it optimize for web.
The best view would be to resize window to mobile size. 
Thanks

**Comment by venkivijay** [comment]
@apgapg Yep I got it... If you have any thought of optimizing it for the web I would love to help... Just let me know... Thanks.

**Comment by apgapg** [comment]
@venkivijay I have optimized this for web
https://apgapg.github.io/flutter_profile/

Let me know if still any issue.

**Comment by venkivijay** [comment]
@apgapg Seems like you shrunk the viewport. It kinda worked. But still, all the testimonials and the fonts and avatar within them are not equal. 
[Screenshot](https://imgur.com/Vo3sjjc)
