### ISSUE TITLE
How did you implement the splash screen?

### ISSUE THREAD

**Issue by gauravmehta13** [apgapg/flutter_profile#7]

**Comment by apgapg** [comment]
See web/index.html Here we define the splash screen before our dart vm loads fully. Also see its css

**Comment by gauravmehta13** [comment]
Is there any tutorial for this? I don't have much knowledge about html and css!

**Comment by apgapg** [comment]
@gauravmehta13 You can take help from the code implemented. See web/index.html and take help from it.

**Comment by gauravmehta13** [comment]
<div class="center">
      <img style="height: 150px;" src="img/logo.png" />
      <div style="margin-top: 8px;"></div>
      <div class="loader"></div>
    </div>
this one?

**Comment by gauravmehta13** [comment]
<div class="center">
      <img style="height: 150px;" src="img/logo.png" />
      <div style="margin-top: 8px;"></div>
      <div class="loader"></div>
    </div>

**Comment by gauravmehta13** [comment]
-<div class="center">
  <img style="height: 150px;" src="img/logo.png" />
 <div style="margin-top: 8px;"></div>
    <div class="loader"></div>
    </div>

**Comment by gauravmehta13** [comment]
i tried but its not working can u please send the code which i need to addd to implement that splash screen

**Comment by gauravmehta13** [comment]
It will be a big help for me if you can make a Pull request for splash screen in this repo https://github.com/gauravmehta13/Portfolio
