### ISSUE TITLE
Splash screen implementation

### ISSUE THREAD

**Issue by gauravmehta13** [apgapg/flutter_profile#8]
It will take only 5 mins to show me wht code to write,
please i need it very badly

**Comment by apgapg** [comment]
Okay will provide the code tomorrow morning.

**Comment by apgapg** [comment]
Its clear in web/index.html
See the div in body. Just copy it and also include css/style stylesheet as in head element

**Comment by gauravmehta13** [comment]
got it thanks

**Comment by apgapg** [comment]
Let me know if any issue

**Comment by gauravmehta13** [comment]
Actually, there is one,
![image](https://user-images.githubusercontent.com/51997260/96082914-c2926c00-0ed9-11eb-81eb-06d6c05a7392.png)
the image is appearing on the top but I want it to be in the center of the screen.

**Comment by gauravmehta13** [comment]
https://github.com/gauravmehta13/Portfolio here is the code for the same

**Comment by gauravmehta13** [comment]
Will do, thanks!!
